// This file simulates loading content dynamically through JavaScript
// In a real application, this would likely be an API call

export async function getHomeContent() {
  // Simulate API delay
  await new Promise((resolve) => setTimeout(resolve, 500))

  return {
    hero: {
      title: "Play Your Favorite ASHA777 Games",
      subtitle: "Play with your favorite casino online games and sports betting",
      primaryButton: "Play Now",
      secondaryButton: "Learn More",
    },
    featuredGames: {
      title: "Featured Games",
      viewAll: "View All Games",
      games: [
        {
          id: "game1",
          title: "3Coin",
          provider: "JILI",
          image: "/game-slots/asha777-3coin.png",
          category: "slots",
          rating: 4.8,
          isHot: true,
        },
        {
          id: "game2",
          title: "Alibaba",
          provider: "JILI",
          image: "/game-slots/asha777-alibaba.png",
          category: "slots",
          rating: 4.5,
        },
        {
          id: "game3",
          title: "3Aztec",
          provider: "JILI",
          image: "/game-slots/asha777-aztec-temples.png",
          category: "slots",
          rating: 4.7,
          isNew: true,
        },
        {
          id: "game4",
          title: "Aviator",
          provider: "JILI",
          image: "/game-slots/asha777-aviator.png",
          category: "slots",
          rating: 4.9,
          isHot: true,
        },
        {
          id: "game5",
          title: "BoxingKing",
          provider: "JILI",
          image: "/game-slots/asha777-boxing-king.png",
          category: "slots",
          rating: 4.6,
        },
        {
          id: "game6",
          title: "Poker Pro",
          provider: "FortuneCoin",
          image: "/game-slots/asha777-coin-fortune.png",
          category: "slots",
          rating: 4.7,
        },
        {
          id: "game7",
          title: "Crazy777",
          provider: "JILI",
          image: "/game-slots/asha777-crazy777.png",
          category: "slots",
          rating: 4.3,
        },
        {
          id: "game8",
          title: "CrazyMoney",
          provider: "JILI",
          image: "/game-slots/asha777-crazy-money.png",
          category: "slots",
          rating: 4.6,
          isNew: true,
        },
        {
          id: "game9",
          title: "CricketSah",
          provider: "JILI",
          image: "/game-slots/asha777-cricketsah75.png",
          category: "slots",
          rating: 4.5,
        },
        {
          id: "game10",
          title: "FortuneGems2",
          provider: "JILI",
          image: "/game-slots/asha777-fortune-gems2.png",
          category: "slots",
          rating: 4.4,
        },
        {
          id: "game11",
          title: "FortuneGems",
          provider: "JILI",
          image: "/game-slots/asha777-fortune-gems.png",
          category: "slots",
          rating: 4.2,
        },
        {
          id: "game12",
          title: "Olympus",
          provider: "Pragmatic",
          image: "/game-slots/asha777-gates-olympus.png",
          category: "slots",
          rating: 4.8,
          isHot: true,
        },
        {
          id: "game13",
          title: "Olympus2",
          provider: "Pragmatic",
          image: "/game-slots/asha777-gates-olympus2.png",
          category: "slots",
          rating: 4.7,
          isNew: true,
        },
        {
          id: "game14",
          title: "Golden",
          provider: "JILI",
          image: "/game-slots/asha777-golden-empire.png",
          category: "slots",
          rating: 4.6,
        },
        {
          id: "game15",
          title: "SpaceMan",
          provider: "Pragmatic",
          image: "/game-slots/asha777-spaceman.png",
          category: "slots",
          rating: 4.9,
          isHot: true,
        },
        {
          id: "game16",
          title: "HighFlyer",
          provider: "Pragmatic",
          image: "/game-slots/asha777-high-flyer.png",
          category: "slots",
          rating: 4.7,
        },
        {
          id: "game17",
          title: "Princess",
          provider: "Pragmatic",
          image: "/game-slots/asha777-starlight-princess.png",
          category: "slots",
          rating: 4.5,
        },
        {
          id: "game18",
          title: "SuperAce",
          provider: "JILI",
          image: "/game-slots/asha777-super-ace.png",
          category: "slots",
          rating: 4.8,
        },
        {
          id: "game19",
          title: "Bonanza",
          provider: "Pragmatic",
          image: "/game-slots/asha777-sweet-bonanza.png",
          category: "slots",
          rating: 4.8,
        },
        {
          id: "game20",
          title: "Bonanza2",
          provider: "Pragmatic",
          image: "/game-slots/asha777-sweet-bonanza2.png",
          category: "slots",
          rating: 4.8,
        },
        {
          id: "game21",
          title: "Wild",
          provider: "Pragmatic",
          image: "/game-slots/asha777-wildbounty.png",
          category: "slots",
          rating: 4.8,
        },
        {
          id: "game22",
          title: "Archery",
          provider: "APGaming",
          image: "/game-sports/asha777-archery.png",
          category: "sports",
          rating: 4.8,
          isHot: true,
        },
        {
          id: "game23",
          title: "Atheletic",
          provider: "APGaming",
          image: "/game-sports/asha777-atheletic.png",
          category: "sports",
          rating: 4.5,
        },
        {
          id: "game24",
          title: "Cockfighting",
          provider: "SVenus",
          image: "/game-sports/asha777-cockfighting.png",
          category: "sports",
          rating: 4.7,
          isNew: true,
        },
        {
          id: "game25",
          title: "Cricket",
          provider: "SABA",
          image: "/game-sports/asha777-cricket.png",
          category: "sports",
          rating: 4.9,
          isHot: true,
        },
        {
          id: "game26",
          title: "Cricket2",
          provider: "SABA",
          image: "/game-sports/asha777-cricket2.png",
          category: "sports",
          rating: 4.6,
        },
        {
          id: "game27",
          title: "Crossfit",
          provider: "FortuneCoin",
          image: "/game-sports/asha777-crossfit.png",
          category: "sports",
          rating: 4.7,
        },
        {
          id: "game28",
          title: "Cycling",
          provider: "APGaming",
          image: "/game-sports/asha777-cycling.png",
          category: "sports",
          rating: 4.3,
        },
        {
          id: "game29",
          title: "Darts",
          provider: "APGaming",
          image: "/game-sports/asha777-darts.png",
          category: "sports",
          rating: 4.6,
          isNew: true,
        },
        {
          id: "game30",
          title: "Floorball",
          provider: "APGaming",
          image: "/game-sports/asha777-floorball.png",
          category: "sports",
          rating: 4.5,
        },
        {
          id: "game31",
          title: "Football",
          provider: "APGaming",
          image: "/game-sports/asha777-football.png",
          category: "sports",
          rating: 4.4,
        },
        {
          id: "game32",
          title: "Lobby",
          provider: "Lucky",
          image: "/game-sports/asha777-game-lobby.png",
          category: "sports",
          rating: 4.2,
        },
        {
          id: "game33",
          title: "Olympics",
          provider: "APGaming",
          image: "/game-sports/asha777-olympics.png",
          category: "sports",
          rating: 4.8,
          isHot: true,
        },
        {
          id: "game34",
          title: "Skeleton",
          provider: "APGaming",
          image: "/game-sports/asha777-skeleton.png",
          category: "sports",
          rating: 4.7,
          isNew: true,
        },
        {
          id: "game35",
          title: "Snooker",
          provider: "APGaming",
          image: "/game-sports/asha777-snooker.png",
          category: "sports",
          rating: 4.6,
        },
        {
          id: "game36",
          title: "Soccer",
          provider: "APGaming",
          image: "/game-sports/asha777-soccer.png",
          category: "sports",
          rating: 4.9,
          isHot: true,
        },
        {
          id: "game37",
          title: "Softball",
          provider: "APGaming",
          image: "/game-sports/asha777-softball.png",
          category: "sports",
          rating: 4.7,
        },
        {
          id: "game38",
          title: "Squash",
          provider: "APGaming",
          image: "/game-sports/asha777-squash.png",
          category: "sports",
          rating: 4.5,
        },
        {
          id: "game39",
          title: "Tennis",
          provider: "APGaming",
          image: "/game-sports/asha777-tennis.png",
          category: "sports",
          rating: 4.8,
        },
        {
          id: "game40",
          title: "Volleyball",
          provider: "APGaming",
          image: "/game-sports/asha777-volleyball.png",
          category: "sports",
          rating: 4.8,
        },
        {
          id: "game41",
          title: "Blackjack",
          provider: "JILI",
          image: "/game-poker/asha777-blackjack.png",
          category: "poker",
          rating: 4.8,
          isHot: true,
        },
        {
          id: "game42",
          title: "Callbreak",
          provider: "JILI",
          image: "/game-poker/asha777-callbreak.png",
          category: "poker",
          rating: 4.5,
        },
        {
          id: "game43",
          title: "Fantan",
          provider: "JILI",
          image: "/game-poker/asha777-fantan.png",
          category: "poker",
          rating: 4.7,
          isNew: true,
        },
        {
          id: "game44",
          title: "Prawn",
          provider: "JILI",
          image: "/game-poker/asha777-fish-prawn.png",
          category: "poker",
          rating: 4.9,
          isHot: true,
        },
        {
          id: "game45",
          title: "Hi Lo",
          provider: "JILI",
          image: "/game-poker/asha777-hi-lo.png",
          category: "poker",
          rating: 4.6,
        },
        {
          id: "game46",
          title: "Horoscope",
          provider: "JILI",
          image: "/game-poker/asha777-horoscope.png",
          category: "poker",
          rating: 4.7,
        },
        {
          id: "game47",
          title: "Ludo",
          provider: "JILI",
          image: "/game-poker/asha777-ludo.png",
          category: "poker",
          rating: 4.3,
        },
        {
          id: "game48",
          title: "PokDeng",
          provider: "JILI",
          image: "/game-poker/asha777-pok-deng.png",
          category: "poker",
          rating: 4.6,
          isNew: true,
        },
        {
          id: "game49",
          title: "PokerRacing",
          provider: "JILI",
          image: "/game-poker/asha777-poker-racing.png",
          category: "poker",
          rating: 4.5,
        },
        {
          id: "game50",
          title: "PVP-Poker",
          provider: "JILI",
          image: "/game-poker/asha777-pvp-poker.png",
          category: "poker",
          rating: 4.4,
        },
        {
          id: "game51",
          title: "TeenPatti",
          provider: "Lucky",
          image: "/game-poker/asha777-teen-patti.png",
          category: "poker",
          rating: 4.2,
        },
        {
          id: "game52",
          title: "Ultimate",
          provider: "JILI",
          image: "/game-poker/asha777-ultimate.png",
          category: "poker",
          rating: 4.8,
          isHot: true,
        },
        {
          id: "game53",
          title: "AndarBahar",
          provider: "JILI",
          image: "/game-live/asha777-andar-bahar.png",
          category: "casino",
          rating: 4.8,
          isHot: true,
        },
        {
          id: "game54",
          title: "Baccarat4",
          provider: "JILI",
          image: "/game-live/asha777-baccarat4.png",
          category: "casino",
          rating: 4.5,
        },
        {
          id: "game55",
          title: "Baccarat5",
          provider: "JILI",
          image: "/game-live/asha777-baccarat5.png",
          category: "casino",
          rating: 4.7,
          isNew: true,
        },
        {
          id: "game56",
          title: "Baccarat6",
          provider: "JILI",
          image: "/game-live/asha777-baccarat6.png",
          category: "casino",
          rating: 4.9,
          isHot: true,
        },
        {
          id: "game57",
          title: "BaccaratB",
          provider: "JILI",
          image: "/game-live/asha777-baccaratB.png",
          category: "casino",
          rating: 4.6,
        },
        {
          id: "game58",
          title: "BaccaratC",
          provider: "JILI",
          image: "/game-live/asha777-baccaratC.png",
          category: "casino",
          rating: 4.7,
        },
        {
          id: "game59",
          title: "Blackjack2",
          provider: "JILI",
          image: "/game-live/asha777-blackjack2.png",
          category: "casino",
          rating: 4.3,
        },
        {
          id: "game60",
          title: "BlackjackPro",
          provider: "JILI",
          image: "/game-live/asha777-blackjack2-pro.png",
          category: "casino",
          rating: 4.6,
          isNew: true,
        },
        {
          id: "game61",
          title: "BlackjackVIP",
          provider: "JILI",
          image: "/game-live/asha777-blackjackVIP.png",
          category: "casino",
          rating: 4.5,
        },
        {
          id: "game62",
          title: "CrazyTimeFun",
          provider: "JILI",
          image: "/game-live/asha777-crazy-fun-time.png",
          category: "casino",
          rating: 4.4,
        },
        {
          id: "game63",
          title: "CrazyTime",
          provider: "Lucky",
          image: "/game-live/asha777-crazy-time.png",
          category: "casino",
          rating: 4.2,
        },
        {
          id: "game64",
          title: "CrazyTimeA",
          provider: "JILI",
          image: "/game-live/asha777-crazy-timeA.png",
          category: "casino",
          rating: 4.8,
          isHot: true,
        },
        {
          id: "game65",
          title: "Lobby",
          provider: "JILI",
          image: "/game-live/asha777-game-lobby.png",
          category: "casino",
          rating: 4.7,
          isNew: true,
        },
        {
          id: "game66",
          title: "GrandKorean",
          provider: "JILI",
          image: "/game-live/asha777-grand-korean.png",
          category: "casino",
          rating: 4.6,
        },
        {
          id: "game67",
          title: "Lucky7",
          provider: "JILI",
          image: "/game-live/asha777-lucky7.png",
          category: "casino",
          rating: 4.9,
          isHot: true,
        },
        {
          id: "game68",
          title: "MegaWheel",
          provider: "JILI",
          image: "/game-live/asha777-mega-wheel.png",
          category: "casino",
          rating: 4.7,
        },
        {
          id: "game69",
          title: "Squash",
          provider: "JILI",
          image: "/game-live/asha777-playboy-speed.png",
          category: "casino",
          rating: 4.5,
        },
        {
          id: "game70",
          title: "RoyalPoker",
          provider: "JILI",
          image: "/game-live/asha777-royal-poker.png",
          category: "casino",
          rating: 4.8,
        },
        {
          id: "game71",
          title: "VietnamSpeed",
          provider: "JILI",
          image: "/game-live/asha777-vietnam-speed.png",
          category: "casino",
          rating: 4.8,
        },
        {
          id: "game72",
          title: "War",
          provider: "JILI",
          image: "/game-live/asha777-war.png",
          category: "casino",
          rating: 4.8,
        },
        {
          id: "game73",
          title: "WonderLand",
          provider: "JILI",
          image: "/game-live/asha777-wonderland.png",
          category: "casino",
          rating: 4.8,
        },
        {
          id: "game74",
          title: "CursedSea",
          provider: "JILI",
          image: "/game-fishing/asha777-cursed-sea.png",
          category: "fishing",
          rating: 4.8,
          isHot: true,
        },
        {
          id: "game75",
          title: "DragonFishing",
          provider: "JILI",
          image: "/game-fishing/asha777-dragon-fishing.png",
          category: "fishing",
          rating: 4.5,
        },
        {
          id: "game76",
          title: "DragonMaster",
          provider: "JILI",
          image: "/game-fishing/asha777-dragon-master.png",
          category: "fishing",
          rating: 4.7,
          isNew: true,
        },
        {
          id: "game77",
          title: "FishingLegend",
          provider: "JILI",
          image: "/game-fishing/asha777-fishing-legend.png",
          category: "fishing",
          rating: 4.9,
          isHot: true,
        },
        {
          id: "game78",
          title: "FishingWar",
          provider: "JILI",
          image: "/game-fishing/asha777-fishing-war.png",
          category: "fishing",
          rating: 4.6,
        },
        {
          id: "game79",
          title: "FishingWar",
          provider: "JILI",
          image: "/game-fishing/asha777-fishing-war.png",
          category: "fishing",
          rating: 4.7,
        },
        {
          id: "game80",
          title: "JackpotFishing",
          provider: "JILI",
          image: "/game-fishing/asha777-jackpot-fishing.png",
          category: "fishing",
          rating: 4.3,
        },
        {
          id: "game81",
          title: "MegaFishing",
          provider: "JILI",
          image: "/game-fishing/asha777-mega-fishing.png",
          category: "fishing",
          rating: 4.6,
          isNew: true,
        },
        {
          id: "game82",
          title: "MonkeyKing",
          provider: "JILI",
          image: "/game-fishing/asha777-monkey-king.png",
          category: "fishing",
          rating: 4.5,
        },
        {
          id: "game83",
          title: "OceanLoot",
          provider: "JILI",
          image: "/game-fishing/asha777-ocean-loot.png",
          category: "fishing",
          rating: 4.4,
        },
        {
          id: "game84",
          title: "OceanVacation",
          provider: "Lucky",
          image: "/game-fishing/asha777-ocean-vacation.png",
          category: "fishing",
          rating: 4.2,
        },
        {
          id: "game85",
          title: "RoyalFishing",
          provider: "JILI",
          image: "/game-fishing/asha777-royal-fishing.png",
          category: "fishing",
          rating: 4.8,
          isHot: true,
        },
        {
          id: "game86",
          title: "SpaceHunter",
          provider: "JILI",
          image: "/game-fishing/asha777-space-hunter.png",
          category: "fishing",
          rating: 4.7,
          isNew: true,
        },
        {
          id: "game87",
          title: "WarTurtle",
          provider: "JILI",
          image: "/game-fishing/asha777-war-turtle.png",
          category: "fishing",
          rating: 4.6,
        },
        {
          id: "game88",
          title: "ZodiacHunter",
          provider: "JILI",
          image: "/game-fishing/asha777-zodiac-hunter.png",
          category: "fishing",
          rating: 4.9,
          isHot: true,
        },
        {
          id: "game89",
          title: "IAeSports",
          provider: "IA",
          image: "/game-esports/asha777-ea-esports.png",
          category: "esports",
          rating: 4.8,
          isHot: true,
        },
        {
          id: "game90",
          title: "SVenus",
          provider: "SVenus",
          image: "/game-esports/asha777-svenus.png",
          category: "esports",
          rating: 4.5,
        },
        {
          id: "game91",
          title: "TFGaming",
          provider: "TFGaming",
          image: "/game-esports/asha777-tfgaming.png",
          category: "esports",
          rating: 4.7,
          isNew: true,
        },
      ],
    },
    promotions: {
      title: "Promotions",
      items: [
        {
          title: "Deposit Bonus",
          description: "Get 100% bonus on your first deposit",
          buttonText: "Claim Now",
        },
        {
          title: "Sign Up Bonus",
          description: "Get Welcome Bonus after your first game",
          buttonText: "Claim Now",
        },
      ],
    },
  }
}

export async function getGamesContent() {
  // Simulate API delay
  await new Promise((resolve) => setTimeout(resolve, 500))

  return {
    title: "Our Games",
    subtitle: "Discover our wide selection of casino games",
    games: [
      {
        id: "game1",
        title: "3Coin",
        provider: "JILI",
        image: "/game-slots/asha777-3coin.png",
        category: "slots",
        rating: 4.8,
        isHot: true,
      },
      {
        id: "game2",
        title: "Alibaba",
        provider: "JILI",
        image: "/game-slots/asha777-alibaba.png",
        category: "slots",
        rating: 4.5,
      },
      {
        id: "game3",
        title: "3Aztec",
        provider: "JILI",
        image: "/game-slots/asha777-aztec-temples.png",
        category: "slots",
        rating: 4.7,
        isNew: true,
      },
      {
        id: "game4",
        title: "Aviator",
        provider: "JILI",
        image: "/game-slots/asha777-aviator.png",
        category: "slots",
        rating: 4.9,
        isHot: true,
      },
      {
        id: "game5",
        title: "BoxingKing",
        provider: "JILI",
        image: "/game-slots/asha777-boxing-king.png",
        category: "slots",
        rating: 4.6,
      },
      {
        id: "game6",
        title: "Poker Pro",
        provider: "FortuneCoin",
        image: "/game-slots/asha777-coin-fortune.png",
        category: "slots",
        rating: 4.7,
      },
      {
        id: "game7",
        title: "Crazy777",
        provider: "JILI",
        image: "/game-slots/asha777-crazy777.png",
        category: "slots",
        rating: 4.3,
      },
      {
        id: "game8",
        title: "CrazyMoney",
        provider: "JILI",
        image: "/game-slots/asha777-crazy-money.png",
        category: "slots",
        rating: 4.6,
        isNew: true,
      },
      {
        id: "game9",
        title: "CricketSah",
        provider: "JILI",
        image: "/game-slots/asha777-cricketsah75.png",
        category: "slots",
        rating: 4.5,
      },
      {
        id: "game10",
        title: "FortuneGems2",
        provider: "JILI",
        image: "/game-slots/asha777-fortune-gems2.png",
        category: "slots",
        rating: 4.4,
      },
      {
        id: "game11",
        title: "FortuneGems",
        provider: "JILI",
        image: "/game-slots/asha777-fortune-gems.png",
        category: "slots",
        rating: 4.2,
      },
      {
        id: "game12",
        title: "Olympus",
        provider: "Pragmatic",
        image: "/game-slots/asha777-gates-olympus.png",
        category: "slots",
        rating: 4.8,
        isHot: true,
      },
      {
        id: "game13",
        title: "Olympus2",
        provider: "Pragmatic",
        image: "/game-slots/asha777-gates-olympus2.png",
        category: "slots",
        rating: 4.7,
        isNew: true,
      },
      {
        id: "game14",
        title: "Golden",
        provider: "JILI",
        image: "/game-slots/asha777-golden-empire.png",
        category: "slots",
        rating: 4.6,
      },
      {
        id: "game15",
        title: "SpaceMan",
        provider: "Pragmatic",
        image: "/game-slots/asha777-spaceman.png",
        category: "slots",
        rating: 4.9,
        isHot: true,
      },
      {
        id: "game16",
        title: "HighFlyer",
        provider: "Pragmatic",
        image: "/game-slots/asha777-high-flyer.png",
        category: "slots",
        rating: 4.7,
      },
      {
        id: "game17",
        title: "Princess",
        provider: "Pragmatic",
        image: "/game-slots/asha777-starlight-princess.png",
        category: "slots",
        rating: 4.5,
      },
      {
        id: "game18",
        title: "SuperAce",
        provider: "JILI",
        image: "/game-slots/asha777-super-ace.png",
        category: "slots",
        rating: 4.8,
      },
      {
        id: "game19",
        title: "Bonanza",
        provider: "Pragmatic",
        image: "/game-slots/asha777-sweet-bonanza.png",
        category: "slots",
        rating: 4.8,
      },
      {
        id: "game20",
        title: "Bonanza2",
        provider: "Pragmatic",
        image: "/game-slots/asha777-sweet-bonanza2.png",
        category: "slots",
        rating: 4.8,
      },
      {
        id: "game21",
        title: "Wild",
        provider: "Pragmatic",
        image: "/game-slots/asha777-wildbounty.png",
        category: "slots",
        rating: 4.8,
      },
      {
        id: "game22",
        title: "Archery",
        provider: "APGaming",
        image: "/game-sports/asha777-archery.png",
        category: "sports",
        rating: 4.8,
        isHot: true,
      },
      {
        id: "game23",
        title: "Atheletic",
        provider: "APGaming",
        image: "/game-sports/asha777-atheletic.png",
        category: "sports",
        rating: 4.5,
      },
      {
        id: "game24",
        title: "Cockfighting",
        provider: "SVenus",
        image: "/game-sports/asha777-cockfighting.png",
        category: "sports",
        rating: 4.7,
        isNew: true,
      },
      {
        id: "game25",
        title: "Cricket",
        provider: "SABA",
        image: "/game-sports/asha777-cricket.png",
        category: "sports",
        rating: 4.9,
        isHot: true,
      },
      {
        id: "game26",
        title: "Cricket2",
        provider: "SABA",
        image: "/game-sports/asha777-cricket2.png",
        category: "sports",
        rating: 4.6,
      },
      {
        id: "game27",
        title: "Crossfit",
        provider: "FortuneCoin",
        image: "/game-sports/asha777-crossfit.png",
        category: "sports",
        rating: 4.7,
      },
      {
        id: "game28",
        title: "Cycling",
        provider: "APGaming",
        image: "/game-sports/asha777-cycling.png",
        category: "sports",
        rating: 4.3,
      },
      {
        id: "game29",
        title: "Darts",
        provider: "APGaming",
        image: "/game-sports/asha777-darts.png",
        category: "sports",
        rating: 4.6,
        isNew: true,
      },
      {
        id: "game30",
        title: "Floorball",
        provider: "APGaming",
        image: "/game-sports/asha777-floorball.png",
        category: "sports",
        rating: 4.5,
      },
      {
        id: "game31",
        title: "Football",
        provider: "APGaming",
        image: "/game-sports/asha777-football.png",
        category: "sports",
        rating: 4.4,
      },
      {
        id: "game32",
        title: "Lobby",
        provider: "Lucky",
        image: "/game-sports/asha777-game-lobby.png",
        category: "sports",
        rating: 4.2,
      },
      {
        id: "game33",
        title: "Olympics",
        provider: "APGaming",
        image: "/game-sports/asha777-olympics.png",
        category: "sports",
        rating: 4.8,
        isHot: true,
      },
      {
        id: "game34",
        title: "Skeleton",
        provider: "APGaming",
        image: "/game-sports/asha777-skeleton.png",
        category: "sports",
        rating: 4.7,
        isNew: true,
      },
      {
        id: "game35",
        title: "Snooker",
        provider: "APGaming",
        image: "/game-sports/asha777-snooker.png",
        category: "sports",
        rating: 4.6,
      },
      {
        id: "game36",
        title: "Soccer",
        provider: "APGaming",
        image: "/game-sports/asha777-soccer.png",
        category: "sports",
        rating: 4.9,
        isHot: true,
      },
      {
        id: "game37",
        title: "Softball",
        provider: "APGaming",
        image: "/game-sports/asha777-softball.png",
        category: "sports",
        rating: 4.7,
      },
      {
        id: "game38",
        title: "Squash",
        provider: "APGaming",
        image: "/game-sports/asha777-squash.png",
        category: "sports",
        rating: 4.5,
      },
      {
        id: "game39",
        title: "Tennis",
        provider: "APGaming",
        image: "/game-sports/asha777-tennis.png",
        category: "sports",
        rating: 4.8,
      },
      {
        id: "game40",
        title: "Volleyball",
        provider: "APGaming",
        image: "/game-sports/asha777-volleyball.png",
        category: "sports",
        rating: 4.8,
      },
      {
        id: "game41",
        title: "Blackjack",
        provider: "JILI",
        image: "/game-poker/asha777-blackjack.png",
        category: "poker",
        rating: 4.8,
        isHot: true,
      },
      {
        id: "game42",
        title: "Callbreak",
        provider: "JILI",
        image: "/game-poker/asha777-callbreak.png",
        category: "poker",
        rating: 4.5,
      },
      {
        id: "game43",
        title: "Fantan",
        provider: "JILI",
        image: "/game-poker/asha777-fantan.png",
        category: "poker",
        rating: 4.7,
        isNew: true,
      },
      {
        id: "game44",
        title: "Prawn",
        provider: "JILI",
        image: "/game-poker/asha777-fish-prawn.png",
        category: "poker",
        rating: 4.9,
        isHot: true,
      },
      {
        id: "game45",
        title: "Hi Lo",
        provider: "JILI",
        image: "/game-poker/asha777-hi-lo.png",
        category: "poker",
        rating: 4.6,
      },
      {
        id: "game46",
        title: "Horoscope",
        provider: "JILI",
        image: "/game-poker/asha777-horoscope.png",
        category: "poker",
        rating: 4.7,
      },
      {
        id: "game47",
        title: "Ludo",
        provider: "JILI",
        image: "/game-poker/asha777-ludo.png",
        category: "poker",
        rating: 4.3,
      },
      {
        id: "game48",
        title: "PokDeng",
        provider: "JILI",
        image: "/game-poker/asha777-pok-deng.png",
        category: "poker",
        rating: 4.6,
        isNew: true,
      },
      {
        id: "game49",
        title: "PokerRacing",
        provider: "JILI",
        image: "/game-poker/asha777-poker-racing.png",
        category: "poker",
        rating: 4.5,
      },
      {
        id: "game50",
        title: "PVP-Poker",
        provider: "JILI",
        image: "/game-poker/asha777-pvp-poker.png",
        category: "poker",
        rating: 4.4,
      },
      {
        id: "game51",
        title: "TeenPatti",
        provider: "Lucky",
        image: "/game-poker/asha777-teen-patti.png",
        category: "poker",
        rating: 4.2,
      },
      {
        id: "game52",
        title: "Ultimate",
        provider: "JILI",
        image: "/game-poker/asha777-ultimate.png",
        category: "poker",
        rating: 4.8,
        isHot: true,
      },
      {
        id: "game53",
        title: "AndarBahar",
        provider: "JILI",
        image: "/game-live/asha777-andar-bahar.png",
        category: "casino",
        rating: 4.8,
        isHot: true,
      },
      {
        id: "game54",
        title: "Baccarat4",
        provider: "JILI",
        image: "/game-live/asha777-baccarat4.png",
        category: "casino",
        rating: 4.5,
      },
      {
        id: "game55",
        title: "Baccarat5",
        provider: "JILI",
        image: "/game-live/asha777-baccarat5.png",
        category: "casino",
        rating: 4.7,
        isNew: true,
      },
      {
        id: "game56",
        title: "Baccarat6",
        provider: "JILI",
        image: "/game-live/asha777-baccarat6.png",
        category: "casino",
        rating: 4.9,
        isHot: true,
      },
      {
        id: "game57",
        title: "BaccaratB",
        provider: "JILI",
        image: "/game-live/asha777-baccaratB.png",
        category: "casino",
        rating: 4.6,
      },
      {
        id: "game58",
        title: "BaccaratC",
        provider: "JILI",
        image: "/game-live/asha777-baccaratC.png",
        category: "casino",
        rating: 4.7,
      },
      {
        id: "game59",
        title: "Blackjack2",
        provider: "JILI",
        image: "/game-live/asha777-blackjack2.png",
        category: "casino",
        rating: 4.3,
      },
      {
        id: "game60",
        title: "BlackjackPro",
        provider: "JILI",
        image: "/game-live/asha777-blackjack2-pro.png",
        category: "casino",
        rating: 4.6,
        isNew: true,
      },
      {
        id: "game61",
        title: "BlackjackVIP",
        provider: "JILI",
        image: "/game-live/asha777-blackjackVIP.png",
        category: "casino",
        rating: 4.5,
      },
      {
        id: "game62",
        title: "CrazyTimeFun",
        provider: "JILI",
        image: "/game-live/asha777-crazy-fun-time.png",
        category: "casino",
        rating: 4.4,
      },
      {
        id: "game63",
        title: "CrazyTime",
        provider: "Lucky",
        image: "/game-live/asha777-crazy-time.png",
        category: "casino",
        rating: 4.2,
      },
      {
        id: "game64",
        title: "CrazyTimeA",
        provider: "JILI",
        image: "/game-live/asha777-crazy-timeA.png",
        category: "casino",
        rating: 4.8,
        isHot: true,
      },
      {
        id: "game65",
        title: "Lobby",
        provider: "JILI",
        image: "/game-live/asha777-game-lobby.png",
        category: "casino",
        rating: 4.7,
        isNew: true,
      },
      {
        id: "game66",
        title: "GrandKorean",
        provider: "JILI",
        image: "/game-live/asha777-grand-korean.png",
        category: "casino",
        rating: 4.6,
      },
      {
        id: "game67",
        title: "Lucky7",
        provider: "JILI",
        image: "/game-live/asha777-lucky7.png",
        category: "casino",
        rating: 4.9,
        isHot: true,
      },
      {
        id: "game68",
        title: "MegaWheel",
        provider: "JILI",
        image: "/game-live/asha777-mega-wheel.png",
        category: "casino",
        rating: 4.7,
      },
      {
        id: "game69",
        title: "Squash",
        provider: "JILI",
        image: "/game-live/asha777-playboy-speed.png",
        category: "casino",
        rating: 4.5,
      },
      {
        id: "game70",
        title: "RoyalPoker",
        provider: "JILI",
        image: "/game-live/asha777-royal-poker.png",
        category: "casino",
        rating: 4.8,
      },
      {
        id: "game71",
        title: "VietnamSpeed",
        provider: "JILI",
        image: "/game-live/asha777-vietnam-speed.png",
        category: "casino",
        rating: 4.8,
      },
      {
        id: "game72",
        title: "War",
        provider: "JILI",
        image: "/game-live/asha777-war.png",
        category: "casino",
        rating: 4.8,
      },
      {
        id: "game73",
        title: "WonderLand",
        provider: "JILI",
        image: "/game-live/asha777-wonderland.png",
        category: "casino",
        rating: 4.8,
      },
      {
        id: "game74",
        title: "CursedSea",
        provider: "JILI",
        image: "/game-fishing/asha777-cursed-sea.png",
        category: "fishing",
        rating: 4.8,
        isHot: true,
      },
      {
        id: "game75",
        title: "DragonFishing",
        provider: "JILI",
        image: "/game-fishing/asha777-dragon-fishing.png",
        category: "fishing",
        rating: 4.5,
      },
      {
        id: "game76",
        title: "DragonMaster",
        provider: "JILI",
        image: "/game-fishing/asha777-dragon-master.png",
        category: "fishing",
        rating: 4.7,
        isNew: true,
      },
      {
        id: "game77",
        title: "FishingLegend",
        provider: "JILI",
        image: "/game-fishing/asha777-fishing-legend.png",
        category: "fishing",
        rating: 4.9,
        isHot: true,
      },
      {
        id: "game78",
        title: "FishingWar",
        provider: "JILI",
        image: "/game-fishing/asha777-fishing-war.png",
        category: "fishing",
        rating: 4.6,
      },
      {
        id: "game79",
        title: "FishingWar",
        provider: "JILI",
        image: "/game-fishing/asha777-fishing-war.png",
        category: "fishing",
        rating: 4.7,
      },
      {
        id: "game80",
        title: "JackpotFishing",
        provider: "JILI",
        image: "/game-fishing/asha777-jackpot-fishing.png",
        category: "fishing",
        rating: 4.3,
      },
      {
        id: "game81",
        title: "MegaFishing",
        provider: "JILI",
        image: "/game-fishing/asha777-mega-fishing.png",
        category: "fishing",
        rating: 4.6,
        isNew: true,
      },
      {
        id: "game82",
        title: "MonkeyKing",
        provider: "JILI",
        image: "/game-fishing/asha777-monkey-king.png",
        category: "fishing",
        rating: 4.5,
      },
      {
        id: "game83",
        title: "OceanLoot",
        provider: "JILI",
        image: "/game-fishing/asha777-ocean-loot.png",
        category: "fishing",
        rating: 4.4,
      },
      {
        id: "game84",
        title: "OceanVacation",
        provider: "Lucky",
        image: "/game-fishing/asha777-ocean-vacation.png",
        category: "fishing",
        rating: 4.2,
      },
      {
        id: "game85",
        title: "RoyalFishing",
        provider: "JILI",
        image: "/game-fishing/asha777-royal-fishing.png",
        category: "fishing",
        rating: 4.8,
        isHot: true,
      },
      {
        id: "game86",
        title: "SpaceHunter",
        provider: "JILI",
        image: "/game-fishing/asha777-space-hunter.png",
        category: "fishing",
        rating: 4.7,
        isNew: true,
      },
      {
        id: "game87",
        title: "WarTurtle",
        provider: "JILI",
        image: "/game-fishing/asha777-war-turtle.png",
        category: "fishing",
        rating: 4.6,
      },
      {
        id: "game88",
        title: "ZodiacHunter",
        provider: "JILI",
        image: "/game-fishing/asha777-zodiac-hunter.png",
        category: "fishing",
        rating: 4.9,
        isHot: true,
      },
      {
        id: "game89",
        title: "IAeSports",
        provider: "IA",
        image: "/game-esports/asha777-ea-esports.png",
        category: "esports",
        rating: 4.8,
        isHot: true,
      },
      {
        id: "game90",
        title: "SVenus",
        provider: "SVenus",
        image: "/game-esports/asha777-svenus.png",
        category: "esports",
        rating: 4.5,
      },
      {
        id: "game91",
        title: "TFGaming",
        provider: "TFGaming",
        image: "/game-esports/asha777-tfgaming.png",
        category: "esports",
        rating: 4.7,
        isNew: true,
      },
    ],
  }
}
